apiVersion: v1
kind: PersistentVolume

metadata:
  name: pv-task3
  labels:
    type: local

spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/sda1/data/task3"
      