apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: pvc-task3
  labels:
    name: pvc-task3

spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi